# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Deploy

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

env:
  DEPLOY_BRANCH: deploy-pages
  deploy_script_version: "v0.0.4"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to gh-pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ env.DEPLOY_BRANCH }}
          publish_dir: upload-file
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: 🚀 Deploying to gh-pages @ ${{ env.GITHUB_SHA }}

      - name: Deploy
        if: ${{ github.event_name != 'pull_request' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            bash <(curl -s -L https://raw.github.com/Dup4/bash-script-snippet/${{ env.deploy_script_version }}/deploy_gh_pages.sh) \
            -r xcpcio/upload-file \
            -d /var/docker-data/nginx/www/xcpcio \
            -b ${{ env.DEPLOY_BRANCH }}
